name: Deploy static site to GCS

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  BUCKET: ${{ secrets.GCS_BUCKET }}
  MAIN_PAGE: index.html
  ERROR_PAGE: 404.html

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (JSON key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Ensure website config
        run: |
          gsutil web set -m "${MAIN_PAGE}" -e "${ERROR_PAGE}" "gs://${BUCKET}"

      - name: Sync files to GCS
        run: |
          SRC="."
          gsutil -m rsync -r -d -x '(^\.git/|^\.github/|^infra/|^\.terraform/|.*\.tf$|README\.md$|.*\.json$)' "$SRC" "gs://${BUCKET}"
          gsutil -m setmeta -r -h "Cache-Control:no-store"  "gs://${BUCKET}/*.html" "gs://${BUCKET}/**.html" || true
          gsutil -m setmeta -r -h "Cache-Control:public,max-age=3600" \
            "gs://${BUCKET}/**.css" "gs://${BUCKET}/**.js" "gs://${BUCKET}/**.png" "gs://${BUCKET}/**.jpg" \
            "gs://${BUCKET}/**.jpeg" "gs://${BUCKET}/**.svg" "gs://${BUCKET}/**.webp" "gs://${BUCKET}/**.ico" "gs://${BUCKET}/**.json" || true

      - name: Show website URL
        run: |
          echo "Deployed to: http://storage.googleapis.com/${BUCKET}/index.html"
